[build]
  command = "yarn build"
  functions = "out_functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  YARN_VERSION = "1.22.21"
  NODE_VERSION = "18"

[dev]
  command = "yarn dev"

[install]
  command = "yarn install"